{"name": "insights.specs.Specs.ls_var_opt_mssql_log", "exec_time": 0.00014925003051757812, "errors": ["Traceback (most recent call last):\n  File \"/var/lib/insights/newest.egg/insights/core/serde.py\", line 191, in dehydrate\n    doc[\"results\"] = marshal(value, root=self.data, pool=self.pool)\n  File \"/var/lib/insights/newest.egg/insights/core/serde.py\", line 106, in marshal\n    return f(v)\n  File \"/var/lib/insights/newest.egg/insights/core/serde.py\", line 85, in serialize\n    \"object\": to_dict(obj, root=root),\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 1012, in serialize_command_output\n    rc = obj.write(dst)\n  File \"/var/lib/insights/newest.egg/insights/core/spec_factory.py\", line 394, in write\n    return p.write(dst, keep_rc=self.keep_rc)\n  File \"/var/lib/insights/newest.egg/insights/util/subproc.py\", line 155, in write\n    six.reraise(be.__class__, be, sys.exc_info()[2])\n  File \"/usr/lib/python3.6/site-packages/six.py\", line 693, in reraise\n    raise value\n  File \"/var/lib/insights/newest.egg/insights/util/subproc.py\", line 151, in write\n    raise CalledProcessError(rc, self.cmds[0], \"\")\ninsights.util.subproc.CalledProcessError: (2, ['timeout', '-s', '9', '120', '/bin/ls', '-la', '/var/opt/mssql/log'], '')\n"], "results": null, "ser_time": 0.004048347473144531}